[package]
name = "rust-gpu-tools"
version = "0.1.1"
authors = ["Keyvan Kambakhsh <keyvankambakhsh@gmail.com>", "porcuquine <porcuquine@gmail.com>"]
description = "Rust OpenCL tools"
edition = "2018"
homepage = "https://github.com/filecoin-project/rust-gpu-tools"
license = "MIT/Apache-2.0"
repository = "https://github.com/filecoin-project/rust-gpu-tools"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl = { version = "0.19.4", package = "fil-ocl" }
dirs = "2.0.2"
sha2 = "0.8.2"
thiserror = "1.0.10"
fs2 = { version = "0.4.3", optional = true }
futures = { version = "0.3.5" }
lazy_static = "1.4.0"
log = "0.4.8"
rand = "0.7.3"
tokio-test = "0.2.1"
# [dev-dependencies]
tempfile = "3"

[features]
default = ["scheduler"]
scheduler = ["fs2"]
